export const BUY_URL = "https://dexscreener.com/";

export const masks = [
  {
    id: "gigachad",
    name: "Gigachad Mask",
    price: 69.0,
    priceLabel: "69.00 $MASK",
    caption: "Jawline protection for peak timeline dominance.",
    image: "/masks/gigachad-mask.jpg",
    category: "Character",
    rarity: "Legendary",
    buyUrl: BUY_URL,
  },
  {
    id: "wojak",
    name: "Wojak Mask",
    price: 13.37,
    priceLabel: "13.37 $MASK",
    caption: "For holders crying through every candle.",
    image: "/masks/wojak-mask.jpg",
    category: "Character",
    rarity: "Common",
    buyUrl: BUY_URL,
  },
  {
    id: "alon",
    name: "Alon Mask",
    price: 42.0,
    priceLabel: "42.00 $MASK",
    caption: "The Mars-grade panic mask for impossible announcements.",
    image: "/masks/alon-mask.jpg",
    category: "Character",
    rarity: "Rare",
    buyUrl: BUY_URL,
  },
  {
    id: "doge",
    name: "Doge Mask",
    price: 420.69,
    priceLabel: "420.69 $MASK",
    caption: "Such protection. Much meme. Very mask.",
    image: "/masks/doge-mask.jpg",
    category: "Animal",
    rarity: "Legendary",
    buyUrl: BUY_URL,
  },
  {
    id: "wif",
    name: "Wif Mask",
    price: 88.88,
    priceLabel: "88.88 $MASK",
    caption: "Still has hat. Still no plan. Still bullish.",
    image: "/masks/wif-mask.jpg",
    category: "Animal",
    rarity: "Rare",
    buyUrl: BUY_URL,
  },
  {
    id: "pudgy",
    name: "Pudgy Mask",
    price: 99.0,
    priceLabel: "99.00 $MASK",
    caption: "Cute enough to survive any outbreak narrative.",
    image: "/masks/pudgy-mask.jpg",
    category: "Character",
    rarity: "Rare",
    buyUrl: BUY_URL,
  },
  {
    id: "rat",
    name: "Rat Mask",
    price: 6.66,
    priceLabel: "6.66 $MASK",
    caption: "Born in the basement. Listed on the marketplace.",
    image: "/masks/rat-mask.jpg",
    category: "Character",
    rarity: "Common",
    buyUrl: BUY_URL,
  },
  {
    id: "troll",
    name: "Troll Mask",
    price: 20.1,
    priceLabel: "20.10 $MASK",
    caption: "Problem, virus?",
    image: "/masks/troll-mask.jpg",
    category: "Meme",
    rarity: "Uncommon",
    buyUrl: BUY_URL,
  },
  {
    id: "epic-smiley",
    name: "Epic Smiley Mask",
    price: 7.77,
    priceLabel: "7.77 $MASK",
    caption: "Maximum optimism, minimum due diligence.",
    image: "/masks/epic-smiley-mask.jpg",
    category: "Meme",
    rarity: "Common",
    buyUrl: BUY_URL,
  },
  {
    id: "virus",
    name: "Virus Mask",
    price: 19.84,
    priceLabel: "19.84 $MASK",
    caption: "The final boss of bad headlines.",
    image: "/masks/virus-mask.jpg",
    category: "Meme",
    rarity: "Uncommon",
    buyUrl: BUY_URL,
  },
  {
    id: "solana",
    name: "Solana Mask",
    price: 5.55,
    priceLabel: "5.55 $MASK",
    caption: "Fast, cheap, occasionally coughing.",
    image: "/masks/solana-mask.jpg",
    category: "Logo",
    rarity: "Common",
    buyUrl: BUY_URL,
  },
  {
    id: "pain",
    name: "Pain Mask",
    price: 0.01,
    priceLabel: "0.01 $MASK",
    caption: "For everyone who bought the top and called it research.",
    image: "/masks/pain-mask.jpg",
    category: "Meme",
    rarity: "Common",
    buyUrl: BUY_URL,
  },
  {
    id: "lv",
    name: "LV Mask",
    price: 999.0,
    priceLabel: "999.00 $MASK",
    caption: "Luxury panic, monogrammed for the apocalypse.",
    image: "/masks/lv-mask.jpg",
    category: "Logo",
    rarity: "Mythic",
    buyUrl: BUY_URL,
  },
  {
    id: "supreme",
    name: "Supreme Mask",
    price: 777.0,
    priceLabel: "777.00 $MASK",
    caption: "Drop culture meets outbreak culture.",
    image: "/masks/supreme-mask.jpg",
    category: "Logo",
    rarity: "Mythic",
    buyUrl: BUY_URL,
  },
  {
    id: "grok",
    name: "Grok Mask",
    price: 101.0,
    priceLabel: "101.00 $MASK",
    caption: "Answers everything except why you aped.",
    image: "/masks/grok-mask.jpg",
    category: "Logo",
    rarity: "Rare",
    buyUrl: BUY_URL,
  },
  {
    id: "telegram",
    name: "Telegram Mask",
    price: 64.0,
    priceLabel: "64.00 $MASK",
    caption: "For alpha groups and quarantine chats.",
    image: "/masks/telegram-mask.jpg",
    category: "Logo",
    rarity: "Uncommon",
    buyUrl: BUY_URL,
  },
  {
    id: "twitter",
    name: "Twitter Mask",
    price: 44.0,
    priceLabel: "44.00 $MASK",
    caption: "Where every symptom becomes a thread.",
    image: "/masks/twitter-mask.jpg",
    category: "Logo",
    rarity: "Uncommon",
    buyUrl: BUY_URL,
  },
];
